version: "3.7"
services:
  pulsar:
    # NOTE: the below image is pulsar-all (instead of pulsar), which has all the
    # built-in connectors pre-bundled
    # https://pulsar.apache.org/docs/en/standalone/#install-builtin-connectors-optional
    image: apachepulsar/pulsar-all:2.6.0
    command: bin/pulsar standalone
    volumes:
      - ./debezium-postgres-source-config.yaml:/debezium-postgres-source-config.yaml
    expose:
      - "6650"
      - "8080"
    networks:
      - default
  source-db1:
    image: postgres:10.7
    environment:
      POSTGRES_USER: experiment
      POSTGRES_PASSWORD: experiment
    # Configure Postgres replication slot. Alternatively, this can be done via postgresql.conf
    # https://debezium.io/documentation/reference/1.0/connectors/postgresql.html#server-configuration
    command: postgres -c wal_level=logical -c max_wal_senders=10 -c max_replication_slots=10
    volumes:
      - ./setup_source_db1.sql:/docker-entrypoint-initdb.d/setup_source_db1.sql
      # TODO: configuration for var/lib/postgresql/data/pg_hba.conf
      # https://debezium.io/documentation/reference/1.0/connectors/postgresql.html#PostgreSQL-permissions
    expose:
      - "5432"
    networks:
      - default
  # TODO: actually set up the sink database
  # sink-db1:
  #   image: postgres:10.7
  #   environment:
  #     POSTGRES_USER: experiment
  #     POSTGRES_PASSWORD: experiment
  #   command: postgres
  #   volumes:
  #     - ./setup_sink_db1.sql:/docker-entrypoint-initdb.d/setup_sink_db1.sql
  #   expose:
  #     - "5432"
  #   networks:
  #     - default
  flink-sql-client:
    build: ./flink-sql-client-image
    depends_on:
      - flink-jobmanager
    environment:
      FLINK_JOBMANAGER_HOST: flink-jobmanager
  flink-jobmanager:
    image: flink:1.12.1-scala_2.11
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
  flink-taskmanager:
    image: flink:1.12.1-scala_2.11
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=3
networks:
  default: {}
